INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Charlie Brown', 2.99, 'Coldplay', 3, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));
INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Changes', 2.99, 'Tupac', 3, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));
INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Lasso', 2.99, 'Pheonix', 3, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));

INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Enterprise JavaBeans', 11.40, 'Oreilly Press', 1, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));
INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Oracle PL/SQL Programming', 23.90, 'Oreilly Press', 1, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));
INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('J2EE Design Patterns', 19.80, 'Oreilly Press', 1, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));

INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Big Mamas House', 11.40, 'Comedy', 2, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));
INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Die Hard', 23.90, 'Action', 2, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));
INSERT INTO PRODUCT (NAME,PRICE,DESCRIPTION,CATEGORY_ID, LAST_UPDATE) VALUES ('Dumb and Dumber', 19.80, 'Comedy', 2, TO_TIMESTAMP('12-SEP-12 10.31.19 AM', 'DD-MON-YY HH.MI.SS AM'));
